### ISSUE TITLE
ORA-01722: wired error found in the log from time to time

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#414]
ERROR:cherrypy.error:Fri Sep 12 10:57:50 2014 dbsException-server-error: DBSReaderModel/listRun. (DatabaseError) ORA-01722: invalid number
"\n    WITH TOKEN_GENERATOR AS (\n    SELECT REGEXP_SUBSTR(:token_0, '[^,]+', 1, LEVEL) token\n        FROM DUAL\n        CONNECT BY LEVEL <= LENGTH(:token_0) - LENGTH(REPLACE(:token_0, ',', '')) + 1\n        )\n\tSELECT DISTINCT FL.RUN_NUM\n\tFROM cms_dbs3_prod_phys03_owner.FILE_LUMIS FL WHERE  fl.RUN_NUM in (SELECT TOKEN FROM TOKEN_GENERATOR) " {'token_0': 'Hydjet1p8_TuneDrum_Quenched_MinBias_2760GeV/pythia_ZToEE_2760GeV_PbPb_Embedded_RECO_v2/USER'}
. Exception trace:
Traceback (most recent call last):
  File "/data/srv/beHG1409e/sw/slc5_amd64_gcc461/cms/dbs3/3.2.5/lib/python2.6/site-packages/dbs/web/DBSReaderModel.py", line 1007, in listRuns
    return self.dbsRun.listRuns(run_num, logical_file_name, block_name, dataset)
  File "/data/srv/beHG1409e/sw/slc5_amd64_gcc461/cms/dbs3/3.2.5/lib/python2.6/site-packages/dbs/business/DBSRun.py", line 38, in listRuns
    ret = self.runlist.execute(conn, run_num, logical_file_name, block_name, dataset, tran)
  File "/data/srv/beHG1409e/sw/slc5_amd64_gcc461/cms/dbs3/3.2.5/lib/python2.6/site-packages/dbs/dao/Oracle/DatasetRun/List.py", line 84, in execute
    cursors = self.dbi.processData(sql, binds, conn, transaction=trans, returnCursor=True)
  File "/data/srv/beHG1409e/sw/slc5_amd64_gcc461/cms/dbs3/3.2.5/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 179, in processData
    returnCursor=returnCursor)
  File "/data/srv/beHG1409e/sw/slc5_amd64_gcc461/cms/dbs3/3.2.5/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 65, in executebinds
    resultProxy = connection.execute(s, b)
  File "/data/srv/beHG1409e/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp8/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 824, in execute
    return Connection.executors[c](self, object, multiparams, params)
  File "/data/srv/beHG1409e/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp8/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 888, in _execute_text
 
raise exc.DBAPIError.instance(statement, parameters, e, connection_invalidated=is_disconnect)
DatabaseError: (DatabaseError) ORA-01722: invalid number
"\n    WITH TOKEN_GENERATOR AS (\n    SELECT REGEXP_SUBSTR(:token_0, '[^,]+', 1, LEVEL) token\n        FROM DUAL\n        CONNECT BY LEVEL <= LENGTH(:token_0) - LENGTH(REPLACE(:token_0, ',', '')) + 1\n        )\n\tSELECT DISTINCT FL.RUN_NUM\n\tFROM cms_dbs3_prod_phys03_owner.FILE_LUMIS FL WHERE  fl.RUN_NUM in (SELECT TOKEN FROM TOKEN_GENERATOR) " {'token_0': 'Hydjet1p8_TuneDrum_Quenched_MinBias_2760GeV/pythia_ZToEE_2760GeV_PbPb_Embedded_RECO_v2/USER'}

**Comment by yuyiguo** [comment]
Checked again and not found ORA-01722. We close this issue. Will open a new one or reopen this one if we find ORA-01722 again.
