### ISSUE TITLE
insertBulkBlock fails due to existent acquisition era

### ISSUE THREAD

**Issue by amaltaro** [dmwm/DBS#489]
Hi Yuyi,

it seems we have a problem with the new release in cmsweb-testbed. I'm getting this error when trying to insert a block in DBS:
```
2015-09-24 07:46:18,439:ERROR:DBSUploadPoller:Error trying to process block /TTJets_MSDecays_matchingup_7TeV-madgraph/DMWM_TEST-MonteCarlo_Ext_ALAN_TEST_StageOut_v3-v1/GEN#efc73ac2-62a2-11e5-9183-00221959e7c0 through DBS.
HTTP Error 400: BlockInsert: Check the spelling of acquisition Era name. The db may already have the same acquisition era, but with different cases.
2015-09-24 07:46:18,440:ERROR:DBSUploadPoller:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.9.patch2/lib/python2.6/site-packages/WMComponent/DBS3Buffer/DBSUploadPoller.py", line 134, in uploadWorker
    dbsApi.insertBulkBlock(blockDump = block)
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 317, in insertBulkBlock
    return self.__callServer("bulkblocks", data=blockDump , callmethod='POST' )
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 193, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 221, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
HTTPError: HTTP Error 400: BlockInsert: Check the spelling of acquisition Era name. The db may already have the same acquisition era, but with different cases.
```

The last line reports same acquisition era with different cases (?) Could you investigate it asap please?
Thanks

**Comment by yuyiguo** [comment]
Alan:

Could you give me the data you were trying to insert? I could not find the acquisition era name in DB.

**Comment by amaltaro** [comment]
Sure, this block
/TTJets_MSDecays_matchingup_7TeV-madgraph/DMWM_TEST-MonteCarlo_Ext_ALAN_TEST_StageOut_v3-v1/GEN#efc73ac2-62a2-11e5-9183-00221959e7c0

which has 
AcqEra=DMWM_TEST
ProcStr=MonteCarlo_Ext_ALAN_TEST_StageOut_v3
PD=TTJets_MSDecays_matchingup_7TeV-madgraph

**Comment by yuyiguo** [comment]
I meant your data block. What is in your data that you gave to DBS to load beside the block name?

**Comment by amaltaro** [comment]
Sorry Yuyi, I was mislead by a logging debug vs info :-)
Here is the full blockdump
```
2015-09-24 09:42:55,376:DEBUG:DBSUploadPoller:About to call insert block with block: {'file_conf_list': [{'app_name': 'cmsRun', 'output_module_label': 'Merged', 'pset_hash': 'GIBBERISH', 'lfn': '/store/backfill/1/DMWM_TEST/TTJets_MSDecays_matchingup_7TeV-madgraph/GEN/MonteCarlo_Ext_ALAN_TEST_StageOut_v3-v1/00000/1CC4F908-A162-E511-AAA5-003048FE2B6C.root', 'release_version': 'CMSSW_5_3_19', 'global_tag': 'START53_LV4::All'}], 'dataset_conf_list': [{'release_version': 'CMSSW_5_3_19', 'pset_hash': 'GIBBERISH', 'app_name': 'cmsRun', 'output_module_label': 'Merged', 'global_tag': 'START53_LV4::All'}], 'file_parent_list': [], 'processing_era': {'create_by': 'WMAgent', 'processing_version': '1', 'description': ''}, 'dataset': {'dataset': '/TTJets_MSDecays_matchingup_7TeV-madgraph/DMWM_TEST-MonteCarlo_Ext_ALAN_TEST_StageOut_v3-v1/GEN', 'physics_group_name': 'NoGroup', 'create_by': 'WMAgent', 'last_modified_by': 'WMAgent', 'processed_ds_name': 'DMWM_TEST-MonteCarlo_Ext_ALAN_TEST_StageOut_v3-v1', 'last_modification_date': 1443105775, 'dataset_access_type': 'PRODUCTION', 'creation_date': 1443105775, 'prep_id': 'TOP-Summer11LegwmLHE-00006', 'data_tier_name': 'GEN'}, 'block': {'create_by': 'WMAgent', 'open_for_writing': 0, 'creation_date': 1443088765L, 'block_name': '/TTJets_MSDecays_matchingup_7TeV-madgraph/DMWM_TEST-MonteCarlo_Ext_ALAN_TEST_StageOut_v3-v1/GEN#efc73ac2-62a2-11e5-9183-00221959e7c0', 'file_count': 1, 'origin_site_name': 'stormfe1.pi.infn.it', 'block_size': 4740427}, 'acquisition_era': {'acquisition_era_name': 'DMWM_TEST', 'start_date': 123456789}, 'primds': {'create_by': 'WMAgent', 'primary_ds_type': 'mc', 'primary_ds_name': 'TTJets_MSDecays_matchingup_7TeV-madgraph', 'creation_date': 1443105775}, 'files': [{'check_sum': '3572959380', 'file_lumi_list': [{'lumi_section_num': 111L, 'run_num': 1L}, {'lumi_section_num': 112L, 'run_num': 1L}, {'lumi_section_num': 113L, 'run_num': 1L}, {'lumi_section_num': 114L, 'run_num': 1L}, {'lumi_section_num': 115L, 'run_num': 1L}, {'lumi_section_num': 116L, 'run_num': 1L}, {'lumi_section_num': 117L, 'run_num': 1L}, {'lumi_section_num': 118L, 'run_num': 1L}, {'lumi_section_num': 119L, 'run_num': 1L}, {'lumi_section_num': 120L, 'run_num': 1L}, {'lumi_section_num': 121L, 'run_num': 1L}, {'lumi_section_num': 122L, 'run_num': 1L}, {'lumi_section_num': 123L, 'run_num': 1L}, {'lumi_section_num': 124L, 'run_num': 1L}, {'lumi_section_num': 125L, 'run_num': 1L}, {'lumi_section_num': 126L, 'run_num': 1L}, {'lumi_section_num': 127L, 'run_num': 1L}, {'lumi_section_num': 128L, 'run_num': 1L}, {'lumi_section_num': 129L, 'run_num': 1L}, {'lumi_section_num': 130L, 'run_num': 1L}, {'lumi_section_num': 131L, 'run_num': 1L}, {'lumi_section_num': 132L, 'run_num': 1L}, {'lumi_section_num': 133L, 'run_num': 1L}, {'lumi_section_num': 134L, 'run_num': 1L}, {'lumi_section_num': 135L, 'run_num': 1L}, {'lumi_section_num': 136L, 'run_num': 1L}, {'lumi_section_num': 137L, 'run_num': 1L}, {'lumi_section_num': 138L, 'run_num': 1L}, {'lumi_section_num': 139L, 'run_num': 1L}, {'lumi_section_num': 140L, 'run_num': 1L}, {'lumi_section_num': 141L, 'run_num': 1L}, {'lumi_section_num': 142L, 'run_num': 1L}, {'lumi_section_num': 143L, 'run_num': 1L}, {'lumi_section_num': 144L, 'run_num': 1L}, {'lumi_section_num': 145L, 'run_num': 1L}, {'lumi_section_num': 146L, 'run_num': 1L}, {'lumi_section_num': 147L, 'run_num': 1L}, {'lumi_section_num': 148L, 'run_num': 1L}, {'lumi_section_num': 149L, 'run_num': 1L}, {'lumi_section_num': 150L, 'run_num': 1L}, {'lumi_section_num': 151L, 'run_num': 1L}, {'lumi_section_num': 152L, 'run_num': 1L}, {'lumi_section_num': 153L, 'run_num': 1L}, {'lumi_section_num': 154L, 'run_num': 1L}, {'lumi_section_num': 155L, 'run_num': 1L}, {'lumi_section_num': 156L, 'run_num': 1L}, {'lumi_section_num': 157L, 'run_num': 1L}, {'lumi_section_num': 158L, 'run_num': 1L}, {'lumi_section_num': 159L, 'run_num': 1L}, {'lumi_section_num': 160L, 'run_num': 1L}], 'adler32': '665067ef', 'event_count': 5000L, 'file_type': 'EDM', 'last_modified_by': 'WMAgent', 'logical_file_name': '/store/backfill/1/DMWM_TEST/TTJets_MSDecays_matchingup_7TeV-madgraph/GEN/MonteCarlo_Ext_ALAN_TEST_StageOut_v3-v1/00000/1CC4F908-A162-E511-AAA5-003048FE2B6C.root', 'file_size': 4740427L, 'last_modification_date': 1443105775, 'auto_cross_section': 0.0}]}
```

**Comment by yuyiguo** [comment]
Alan:

I was bale to insert the above block into my VM test bed. Then after I closly looked at the data block and what in the cmsweb-testbed DBS. I found there is already a acquisition era name called  DMWM_Test with id 420262. You were trying to insert an acquisition era named DMWM_TEST. This is not allowed in DBS. You may change the name to DMWM_Test or DMWM_TEST2 or somthing alike. Note the DB has DMWMTest as acquisition era name too. 

Please try again and let me know your result.

**Comment by yuyiguo** [comment]
I was able to not " bale to"

**Comment by amaltaro** [comment]
Hmmm, I did not know DBS was case insensitive. Are there any other fields that follow the same rule (PD, ProcStr, etc)?

**Comment by yuyiguo** [comment]
No. DBS is not case insensitive. It is case sensitive. But we don't allow ambiguous names.Because it will confusing people, for example if one acquisition era called Summer2015 and another one called summer2015. Then people will ask  if these are the same acquisition era? which one I should use? All data in DBS is case sensitive. We had discussion many years ago if we should treat acquisition era like data tier,  the conclusion is that one can pick up how you want to case the name, but as soon as you made it into DBS, you have to stick with the case you choice, That is why DMWM_TEST and DMWM_Test cannot be both in DBS. 

I hope I made it clear.-:)

**Comment by amaltaro** [comment]
Yep! It makes sense to me. Does the same logic also applies to ProcStr or only AcqEra?

**Comment by yuyiguo** [comment]
Only AcqEra.

**Comment by amaltaro** [comment]
Ok, thanks Yuyi and sorry for the false alarm :(
I'm closing this ticket.
