### ISSUE TITLE
cleanup log file: (not an urgent matter) the Traceback is not necessay since the error will be ignore anyway.

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#499]
--------------------getResource--  Mon Oct 12 09:14:04 2015 Migration request ID: 70135
--------------------Mon Oct 12 09:14:04 2015 Inserting block: /DoubleMuon/Run2015D-v1/RAW#abf2037a-5f11-11e5-824b-001e67ac06a0 for request id: 70135
Mon Oct 12 09:14:04 2015 dbsException-invalid-input2: DBSBlockInsert/insertBlock. Block /DoubleMuon/Run2015D-v1/RAW#abf2037a-5f11-11e5-824b-001e67ac06a0 already exists.
Traceback (most recent call last):
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/cms/dbs3-migration/3.3.103/xlib/python2.6/site-packages/dbs/business/DBSBlockInsert.py", line 136, in insertBlockFile
    self.blockin.execute(conn, block, tran)
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/cms/dbs3-migration/3.3.103/xlib/python2.6/site-packages/dbs/dao/Oracle/Block/Insert.py", line 19, in execute
    self.executeSingle(conn, daoinput, "BLOCKS", transaction)
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/cms/dbs3-migration/3.3.103/xlib/python2.6/site-packages/dbs/dao/Oracle/InsertTable/Insert.py", line 30, in executeSingle
    self.dbi.processData(sql, daoinput, conn, transaction)
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/cms/dbs3-migration/3.3.103/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 179, in processData
    returnCursor=returnCursor)
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/cms/dbs3-migration/3.3.103/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 65, in executebinds
    resultProxy = connection.execute(s, b)
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/external/py2-sqlalchemy/0.9.6-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/external/py2-sqlalchemy/0.9.6-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/external/py2-sqlalchemy/0.9.6-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/external/py2-sqlalchemy/0.9.6-comp7/lib/python2.6/site-packages/sql
alchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/external/py2-sqlalchemy/0.9.6-comp7/lib/python2.6/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/external/py2-sqlalchemy/0.9.6-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/data/srv/HG1510/sw.pre.yuyi/slc6_amd64_gcc481/external/py2-sqlalchemy/0.9.6-comp7/lib/python2.6/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) ORA-00001: unique constraint (CMS_DBS3_LOCAL2.TUC_BK_BLOCK_NAME) violated
 ' insert into cms_dbs3_local2.BLOCKS( BLOCK_ID,CREATE_BY,OPEN_FOR_WRITING,LAST_MODIFIED_BY,CREATION_DATE,BLOCK_NAME,FILE_COUNT,ORIGIN_SITE_NAME,LAST_MODIFICATION_DATE,DATASET_ID,BLOCK_SIZE)  values(:block_id,:create_by,:open_for_writing,:last_modified_by,:creation_date,:block_name,:file_count,:origin_site_name,:last_modification_date,:dataset_id,:block_size )' {'block_id': 237346, 'create_by': 'tier0@vocms15.cern.ch', 'open_for_writing': 0, 'last_modified_by': 'tier0@vocms15.cern.ch', 'creation_date': 1442876746, 'block_name': '/DoubleMuon/Run2015D-v1/RAW#abf2037a-5f11-11e5-824b-001e67ac06a0', 'file_count': 59, 'origin_site_name': 'eoscmsftp.cern.ch', 'last_modification_date': 1442876746, 'dataset_id': 280148, 'block_size': 228811675405}
YYYYYYYYYYYYYYYYYYYYMon Oct 12 09:14:04 2015(400, 'DBSBlockInsert/insertBlock. Block /DoubleMuon/Run2015D-v1/RAW#abf2037a-5f11-11e5-824b-001e67ac06a0 already exists.')
--------------------Mon Oct 12 09:14:04 2015 Done insert block: /DoubleMuon/Run2015D-v1/RAW#abf2037a-5f11-11e5-824b-001e67ac06a0 for request id: 70135
--------------------Mon Oct 12 09:14:05 2015 Inserting block: /DoubleMuon/Run2015D-v1/RAW#c6807d00-6b89-11e5-8159-001e67ac06a0 for request id: 70135

**Comment by yuyiguo** [comment]
This is not from DBS, but from WMCore. It dumped this to log anyway even if DBS already handle the unique constraint  error and not record it into log. Not much we can do.
